name: Build code, run unit tests, run SAST, SCA, DAST security scans for .Net/C#
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    name: Run unit tests and SAST scan on the source code 
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.x
    - name: Restore dependencies and build
      run: dotnet restore && dotnet build
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.organization=decsecopscproject
          -Dsonar.projectKey=decsecopscproject

  security:
    runs-on: ubuntu-latest
    name: Run the SCA scan on the source code
    needs: build  # Specify the dependency on the 'build' job
    steps:
      - uses: actions/checkout@v2
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/dotnet@master
        with:
          ignore-failures: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  zap_scan:
    runs-on: ubuntu-latest
    needs: security
    name: Run DAST scan on the web application
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.6.1
        with:
          ref: main
          docker_name: 'owasp/zap2docker-stable'
          target: 'http://example.com/'  # Update with your web application URL
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
